version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      # Prefix all commit messages with "npm"
      prefix: "chore(deps): "
      prefix-development: "chore(dev-deps): "
      include: "scope"
    target-branch: "next"
